version: "3.8"
services:

  consul:
    image: hashicorp/consul:1.20.5
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0
    networks:
      - app-net

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    depends_on:
      - consul
    ports:
      - "8080:8080"
    networks:
      - app-net

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      - consul
    ports:
      - "8081:8081"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge