server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        register-health-check: true
        health-check-path: /actuator/health
        health-check-interval: 20s
        prefer-ip-address: false  # The hostname will be used
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/users/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
                methods: GET,POST
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 500ms
                  factor: 2
                  basedOnPreviousValue: true
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/user-service-fallback

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG


# Resilience4J (CircuitBreaker)
resilience4j.circuitbreaker:
  instances:
    userServiceCircuitBreaker:
      registerHealthIndicator: true
      failureRateThreshold: 50
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 2000ms
      permittedNumberOfCallsInHalfOpenState: 10
      maxWaitDurationInHalfOpenState: 10s
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true

#Fallback Routes (For CircuitBreaker)
#These routes will redirect to local controllers that will be called when the CircuitBreaker is triggered.
#In this example, the controllers are assumed to return simple messages.
#In real applications, you can implement more meaningful fallback logic.
#For instance, returning data from a cache, displaying a static page, etc.
#You will need to create the necessary classes for these controllers.